# Generated by Django 5.0.4 on 2024-05-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webMarket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendecompra',
            name='productos',
            field=models.ManyToManyField(related_name='orden_compra', to='webMarket.producto'),
        ),
    ]
