# Generated by Django 5.0.6 on 2024-07-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webMarket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='estado',
            field=models.CharField(default='Por entregar', max_length=20),
        ),
    ]
