# Generated by Django 5.0.6 on 2024-06-04 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webMarket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='cantidad',
        ),
    ]
