# Generated by Django 5.0.4 on 2024-07-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webMarket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
        migrations.AddField(
            model_name='factura',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
