# Generated by Django 5.0.4 on 2024-07-03 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webMarket', '0002_factura_direccion_factura_foto_factura_rut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='webMarket/static/img/'),
        ),
    ]
