# Generated by Django 5.0.6 on 2024-07-02 19:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webMarket', '0002_factura_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=20)),
                ('motivo', models.TextField()),
                ('fecha_cambio', models.DateTimeField(default=django.utils.timezone.now)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_estado', to='webMarket.factura')),
            ],
        ),
    ]
