# Generated by Django 5.0.4 on 2024-07-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webMarket', '0003_alter_factura_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado',
            field=models.CharField(default='Por Entregar', max_length=20),
        ),
    ]
