# Generated by Django 5.0.6 on 2024-06-04 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webMarket', '0003_usuario_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
    ]
