# Generated by Django 5.0.6 on 2024-06-04 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webMarket', '0005_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritodecompra',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webMarket.usuario'),
        ),
    ]
