# Generated by Django 5.0.6 on 2024-06-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webMarket', '0006_alter_carritodecompra_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordendecompra',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
