# Generated by Django 5.0.6 on 2024-06-04 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webMarket', '0007_ordendecompra_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='orden_de_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='webMarket.ordendecompra'),
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
